module.exports = {
  mySidebar: [
    'index',
    'release-notes',
    {
      type: 'category', 
      label: 'Concepts',
      collapsed: false,
      items: [
        'components',
        'file-locations',
        {
          type: 'category', 
          label: 'Automation Concepts',
          collapsed: false,
          items: [
            'automation-concepts/master-vs-daily',
            'automation-concepts/editing-master-vs-daily',
            'automation-concepts/named-schedule-instances',
            'automation-concepts/frequencies',
            'automation-concepts/property-expressions',
            'automation-concepts/time-zones',
            'automation-concepts/machine-groups',
            'automation-concepts/null-jobs',
            'automation-concepts/file-transfer-jobs',
            'automation-concepts/job-tracking',
            'automation-concepts/embedded-scripts',
          ], 
        },
        'administration/server-options',
        {
          type: 'category', 
          label: 'Users and Roles',
          collapsed: false,
          items: [
            'administration/user-accounts',
            'administration/roles',
            'administration/privileges',
          ], 
        },
        {
          type: 'category', 
          label: 'OpCon Objects',
          collapsed: false,
          items: [
            'objects/schedules',
            'objects/jobs',
            'objects/machines',
            'objects/machine-groups',
            'objects/remote-instances',
            'objects/properties',
            'objects/thresholds',
            'objects/resources',
            'objects/calendars',
            'objects/access-codes',
            'objects/departments',
          ], 
        },
        {
          type: 'category', 
          label: 'Job Components',
          collapsed: false,
          items: [
            'job-components/overview',
            'job-components/instances',
            'job-components/frequency',
            'job-components/events',
            'job-components/threshold-resource-updates',
            'job-components/job-dependencies',
            'job-components/threshold-resource-dependencies',
            'job-components/expression-dependencies',
            'job-components/documentation',
            'job-components/tags',
          ], 
        },
        {
          type: 'category', 
          label: 'Job Types',
          collapsed: false,
          items: [
            'job-types/bis',
            'job-types/container',
            'job-types/file-transfer',
            'job-types/ibm-i',
            'job-types/java',
            'job-types/mcp',
            'job-types/null',
            'job-types/os-2200',
            'job-types/sap-bw',
            'job-types/sap',
            'job-types/sql',
            'job-types/tuxedo-art',
            'job-types/unix',
            'job-types/windows',
            'job-types/zos',
          ], 
        },
      ], 
    },
    {
      type: 'category', 
      label: 'Installation',
      collapsed: false,
      items: [
        'installation/whats-new',
        'installation/breaking-changes',
        'installation/system-requirements',
        'installation/install',
        'installation/upgrade',
        'installation/configuration',
        'installation/components',
        'installation/docker',
        'installation/database-scripts',
      ], 
    },
    {
      type: 'category', 
      label: 'OpCon Events',
      collapsed: false,
      items: [
        'events/introduction',
        'events/defining',
        'events/types',
      ], 
    }, 
    {
      type: 'category', 
      label: 'Reports',
      collapsed: false,
      items: [
        'reports/overview',
        'reports/predefined',
        'reports/custom',
      ], 
    },
    {
      type: 'category', 
      label: 'Server Programs',
      collapsed: false,
      items: [
        'server-programs/introduction',
        'server-programs/licensing',
        'server-programs/service-manager',
        'server-programs/schedule-activity-monitor',
        'server-programs/network-communications',
        'server-programs/notify-handler',
        'server-programs/request-router',
        'server-programs/start-time-calculator',
        'server-programs/optional',
        'server-programs/configuration',
        'server-programs/logging',
      ], 
    },  
  ],
};
